name: sayhello
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  image_picker: 0.4.10
  google_sign_in: 3.2.4
  firebase_analytics: 1.1.0
  firebase_auth: 0.6.6
  firebase_database: 1.0.5
  cloud_firestore: ^0.8.2+3
  firebase_storage: 1.0.4
  firebase_core: ^0.2.5
  cupertino_icons: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

